<?php
// $Id$

// Implement hook_og_links_alter
function og_my_mods_og_links_alter(&$links, $node)
{
  // Using Drupal for Firebug to inspect stuff:
  //firep( $node, "node");
  //firep( $links, "links");

  // don't do anything if user is not a member
  if ( ! og_is_group_member($node) && ! og_is_group_admin($node) ) return;
//drupal_set_message(print_r($node));
global $user;
//drupal_set_message(print_r($user->og_groups[$node->nid]['is_active']));
//drupal_set_message($node->og_selective." - ".OG_OPEN);
  // remove some links
/*  unset($links["create_poll"]);
  unset($links["create_image"]);
  unset($links["create_forum"]);*/
//  unset($links['manager']);

// don't show members link if the group has open membership policy
// and don't show if the user is not an approved member
   if($node->og_selective == OG_OPEN || $user->og_groups[$node->nid]['is_active'] != 1 ) {
  unset($links['invite']);
  unset($links['subscribers']);
  }

// modify create project_issue link
  // if there is a project associated with this group (there assumed to be only one)
  if ( isset($node->field_project_node) ) {
    $pid = $node->field_project_node[0]['nid'];
    // some users can't create issues
    if ( isset($links['create_project_issue']) )
      $links['create_project_issue'] = l(t('Create Issue'), "node/add/project-issue/$pid",
                                       array("query"=>array("gids[]"=>"$node->nid"))
                                         );
  } else {
       unset($links['create_project_issue']);
  }
 

  // Add Trac link(s)
  if ( isset($node->field_tracurl) && $node->field_tracurl[0]['url'] )
    $links['trac'] = l(t('Trac'), $node->field_tracurl[0]['url'] );

  // Add all posts link
//$links['all_posts'] =  l(t('All posts'), "node/$node->nid/search");

  // etc...
}
?>